### ISSUE TITLE
rust-webvr shouldn't rely on features to conditionally export a single backend

### ISSUE THREAD

**Issue by nox** [MortimerGoro/rust-webvr#16]
Cargo features are supposed to be additive and are misused in this crate, for example the following command will fail on Android:

```
cargo build --features "googlevr oculusvr"
```

**Comment by MortimerGoro** [comment]
Hi, 

The additive feature compilation should work for including both backends (and the 

```
cargo build --features "googlevr oculusvr" --target=arm-linux-androideabi
   Compiling bitflags v1.0.1
   Compiling libc v0.2.36
   Compiling cfg-if v0.1.2
   Compiling cc v1.0.6
   Compiling gvr-sys v0.7.0
   Compiling ovr-mobile-sys v0.4.0
   Compiling khronos_api v2.1.0
   Compiling android_injected_glue v0.2.3
   Compiling log v0.4.1
   Compiling xml-rs v0.7.0
   Compiling time v0.1.39
   Compiling libloading v0.5.0
   Compiling rust-webvr-api v0.9.2
   Compiling gl_generator v0.9.0
   Compiling rust-webvr v0.9.10 (file:///home/mortimer/Projects/rust-webvr/rust-webvr)
    Finished dev [unoptimized + debuginfo] target(s) in 9.32 secs
```
Could you share the compilation error? (I tested compilation on Ubuntu 16.04)

If we want to separate the backeds to different crates the api also has a register method which can be called manually (I used that for NDA backends)

**Comment by nox** [comment]
Mmmh I was blind and had local changes where I named both the googlevr and oculusvr stuff the same way, disregard that…
